[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"


[functions]
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-lighthouse"

# optional, deploy the lighthouse report to a path under your site
[plugins.inputs.audits]
  output_path = "reports/lighthouse.html"